name: Suggest a curriculum-wide improvement
description: Tell us about how the content of the curriculum as a whole could be improved
body:
  - type: textarea
    id: details
    attributes:
      label: How could the content be improved?
      description: Please provide details of the improvement you are suggesting, to make it easier for the maintainers and other community members to address the issue.
    validations:
      required: true
  - type: markdown
    attributes:
      value: >
        Thank you for taking time to suggest an improvement to this repository!
