name: Workshop Details and Feedback
description: Share details, number of participants and feedback from a workshop that you are planning to deliver of have delivered this lesson.
title: "[Workshop details and feedback]: "
labels: ["type:discussion"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for planning to teach this lesson and agreeing to share feedback! 
        Please answer the questions below, 
        and note that feedback submitted with this form will be publicly visible.
        If you do not have any feedback to share at the moment (e.g. you have not delivered the workshop yet) - 
        you can come back to this issue later and fill in the missing details.
  - type: textarea
    id: workshop
    attributes:
      label: 1. Workshop details
      description: |
        Tell us about the workshop. 
        When and where is it taking place/where did it take place? Who will host/hosted it? Who were the Instructors? 
        How many Learners were there? What the background of the Learners e.g. their career stage, domain, prior knowledge of the lesson topic, etc?
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Instructor Feedback
  - type: textarea
    id: instructor-up
    attributes:
      label: 2. What did the Instructors find worked well when teaching the lesson? 
      description: |
        What was good about the content and/or the design of the lesson?
    validations:
      required: true
  - type: textarea
    id: instructor-down
    attributes:
      label: 3. What did the Instructors find that could be improved in the lesson?
    validations:
      required: true
  - type: textarea
    id: instructor-other
    attributes:
      label: 4. Do the Instructors have any other feedback on the lesson?
  - type: dropdown
    id: time
    attributes:
      label: 5. Were the Instructors able to teach the whole lesson in the time available?
      options:
        - "Not sure"
        - "Yes"
        - "No"
    validations:
      required: true
  - type: textarea
    id: time-details
    attributes:
      label: 6. Tell us more about the lesson duration
      description: |
        If the Instructors were not able to teach the complete lesson in the time available, how much time did they have and how far through the lesson did they get?
        What content, if any, did they skip when teaching the lesson?
        If they were able to teach the whole lesson, how much time did it take?
        If an episode-by-episode breakdown of the time taken was recorded, please share it here.
  - type: markdown
    attributes:
      value: |
        ## Learner Feedback
  - type: textarea
    id: learner-feedback
    attributes:
      label: 7. Please share any feedback collected from Learners during the lesson pilot.
      description: |
        Feel free to exclude any feedback that is specific to the Instructors, venue, etc, or about other lessons taught at the workshop.
  - type: markdown
    attributes:
      value: |
        ## Conclusion
  - type: textarea
    id: other
    attributes:
      label: 8. Is there anything else you would like to tell us?
